//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Date 的當地語系化字串。
        /// </summary>
        public static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        public static string Signature_already_exists
        {
            get
            {
                return ResourceManager.GetString("Signature_already_exists", resourceCulture);
            }
        }
        public static string have_restock_order
        {
            get
            {
                return ResourceManager.GetString("have_restock_order", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 error 的當地語系化字串。
        /// </summary>
        public static string _error {
            get {
                return ResourceManager.GetString("_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order 的當地語系化字串。
        /// </summary>
        public static string _Order {
            get {
                return ResourceManager.GetString("_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Department 的當地語系化字串。
        /// </summary>
        public static string Add_Department {
            get {
                return ResourceManager.GetString("Add_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add New Spare 的當地語系化字串。
        /// </summary>
        public static string Add_New_Spare {
            get {
                return ResourceManager.GetString("Add_New_Spare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add SaleArea 的當地語系化字串。
        /// </summary>
        public static string Add_SaleArea {
            get {
                return ResourceManager.GetString("Add_SaleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Warehouse 的當地語系化字串。
        /// </summary>
        public static string Add_Warehouse {
            get {
                return ResourceManager.GetString("Add_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All fuck up 的當地語系化字串。
        /// </summary>
        public static string All_fuck_up {
            get {
                return ResourceManager.GetString("All_fuck_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 all warehouse 的當地語系化字串。
        /// </summary>
        public static string all_warehouse {
            get {
                return ResourceManager.GetString("all_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to change your password? 的當地語系化字串。
        /// </summary>
        public static string Are_you_sure_you_want_to_chang {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to change it? 的當地語系化字串。
        /// </summary>
        public static string Are_you_sure_you_want_to_chang0 {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_chang0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete the supplier? 的當地語系化字串。
        /// </summary>
        public static string Are_you_sure_you_want_to_delet {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete it? 的當地語系化字串。
        /// </summary>
        public static string Are_you_sure_you_want_to_delet0 {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to receive it? 的當地語系化字串。
        /// </summary>
        public static string Are_you_sure_you_want_to_recei {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_recei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to remove all items from your cart? 的當地語系化字串。
        /// </summary>
        public static string Are_you_sure_you_want_to_remov {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_remov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 can not get price 的當地語系化字串。
        /// </summary>
        public static string can_not_get_price {
            get {
                return ResourceManager.GetString("can_not_get_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 can not get stock 的當地語系化字串。
        /// </summary>
        public static string can_not_get_stock {
            get {
                return ResourceManager.GetString("can_not_get_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can not print now 的當地語系化字串。
        /// </summary>
        public static string Can_not_print_now {
            get {
                return ResourceManager.GetString("Can_not_print_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot select the location to be deleted! 的當地語系化字串。
        /// </summary>
        public static string Cannot_select_the_location_to_ {
            get {
                return ResourceManager.GetString("Cannot_select_the_location_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collect Spare 的當地語系化字串。
        /// </summary>
        public static string Collect_Spare {
            get {
                return ResourceManager.GetString("Collect_Spare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 companyName 的當地語系化字串。
        /// </summary>
        public static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Condition:  的當地語系化字串。
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Condition: 的當地語系化字串。
        /// </summary>
        public static string Condition0 {
            get {
                return ResourceManager.GetString("Condition0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contact Us 的當地語系化字串。
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data sources are not properly initialized. 的當地語系化字串。
        /// </summary>
        public static string Data_sources_are_not_properly_ {
            get {
                return ResourceManager.GetString("Data_sources_are_not_properly_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DEALER CODE 的當地語系化字串。
        /// </summary>
        public static string DEALER_CODE {
            get {
                return ResourceManager.GetString("DEALER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 dealer must have a saleArea! 的當地語系化字串。
        /// </summary>
        public static string dealer_must_have_a_saleArea {
            get {
                return ResourceManager.GetString("dealer_must_have_a_saleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dealer name: 的當地語系化字串。
        /// </summary>
        public static string Dealer_name {
            get {
                return ResourceManager.GetString("Dealer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DealerID 的當地語系化字串。
        /// </summary>
        public static string DealerID {
            get {
                return ResourceManager.GetString("DealerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DELIVERY ADDRESS (IF DIFFERENT) 的當地語系化字串。
        /// </summary>
        public static string DELIVERY_ADDRESS_IF_DIFFERENT {
            get {
                return ResourceManager.GetString("DELIVERY_ADDRESS_IF_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delivery address not yet recorded. 的當地語系化字串。
        /// </summary>
        public static string Delivery_address_not_yet_recor {
            get {
                return ResourceManager.GetString("Delivery_address_not_yet_recor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DeliveryAddress 的當地語系化字串。
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Department ID already exists. Please choose a different ID. 的當地語系化字串。
        /// </summary>
        public static string Department_ID_already_exists_P {
            get {
                return ResourceManager.GetString("Department_ID_already_exists_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Department ID cannot exceed 5 characters. Please re-enter. 的當地語系化字串。
        /// </summary>
        public static string Department_ID_cannot_exceed_5_ {
            get {
                return ResourceManager.GetString("Department_ID_cannot_exceed_5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Despatch Foreman 的當地語系化字串。
        /// </summary>
        public static string Despatch_Foreman {
            get {
                return ResourceManager.GetString("Despatch_Foreman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Despatch Instruction Set 的當地語系化字串。
        /// </summary>
        public static string Despatch_Instruction_Set {
            get {
                return ResourceManager.GetString("Despatch_Instruction_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to change the data? 的當地語系化字串。
        /// </summary>
        public static string Do_you_want_to_change_the_data {
            get {
                return ResourceManager.GetString("Do_you_want_to_change_the_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to turn to the next page? 的當地語系化字串。
        /// </summary>
        public static string Do_you_want_to_turn_to_the_nex {
            get {
                return ResourceManager.GetString("Do_you_want_to_turn_to_the_nex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Duplicate phone numbers 的當地語系化字串。
        /// </summary>
        public static string Duplicate_phone_numbers {
            get {
                return ResourceManager.GetString("Duplicate_phone_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Department 的當地語系化字串。
        /// </summary>
        public static string Edit_Department {
            get {
                return ResourceManager.GetString("Edit_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit SaleArea 的當地語系化字串。
        /// </summary>
        public static string Edit_SaleArea {
            get {
                return ResourceManager.GetString("Edit_SaleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Spare 的當地語系化字串。
        /// </summary>
        public static string Edit_Spare {
            get {
                return ResourceManager.GetString("Edit_Spare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Warehouse 的當地語系化字串。
        /// </summary>
        public static string Edit_Warehouse {
            get {
                return ResourceManager.GetString("Edit_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: Can not connect server
        ///Please call technician for help. 的當地語系化字串。
        /// </summary>
        public static string Error_Can_not_connect_server_P {
            get {
                return ResourceManager.GetString("Error_Can_not_connect_server_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Generate Spare QR-code 的當地語系化字串。
        /// </summary>
        public static string Generate_Spare_QR_code {
            get {
                return ResourceManager.GetString("Generate_Spare_QR_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Grams: LegendMC 的當地語系化字串。
        /// </summary>
        public static string Grams_LegendMC {
            get {
                return ResourceManager.GetString("Grams_LegendMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 In transit 的當地語系化字串。
        /// </summary>
        public static string In_transit {
            get {
                return ResourceManager.GetString("In_transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid access level. Please enter a valid integer value between 0 and 10000. 的當地語系化字串。
        /// </summary>
        public static string Invalid_access_level_Please_en {
            get {
                return ResourceManager.GetString("Invalid_access_level_Please_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid ContantNumber. Please enter a valid number. 的當地語系化字串。
        /// </summary>
        public static string Invalid_ContantNumber_Please_e {
            get {
                return ResourceManager.GetString("Invalid_ContantNumber_Please_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid input. Please enter a valid number. 的當地語系化字串。
        /// </summary>
        public static string Invalid_input_Please_enter_a_v {
            get {
                return ResourceManager.GetString("Invalid_input_Please_enter_a_v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid input. Please enter a valid number with up to 20 digits. 的當地語系化字串。
        /// </summary>
        public static string Invalid_input_Please_enter_a_v0 {
            get {
                return ResourceManager.GetString("Invalid_input_Please_enter_a_v0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 INVOICE ADDRESS 的當地語系化字串。
        /// </summary>
        public static string INVOICE_ADDRESS {
            get {
                return ResourceManager.GetString("INVOICE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 InvoiceDate 的當地語系化字串。
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to remove {0}:{1} from your cart? 的當地語系化字串。
        /// </summary>
        public static string IS_Are_you_sure_you_want_to_re {
            get {
                return ResourceManager.GetString("IS_Are_you_sure_you_want_to_re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DELETE FROM Cart WHERE SpareID = &apos;{0}&apos; AND UserID = {1}; 的當地語系化字串。
        /// </summary>
        public static string IS_DELETE_FROM_Cart_WHERE_Spar {
            get {
                return ResourceManager.GetString("IS_DELETE_FROM_Cart_WHERE_Spar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error: {0} is already in your shopping cart 的當地語系化字串。
        /// </summary>
        public static string IS_Error_0_is_already_in_your_ {
            get {
                return ResourceManager.GetString("IS_Error_0_is_already_in_your_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not enough stock for {0}:{1}
        /// Only can order {2}
        ///Still placing order? 的當地語系化字串。
        /// </summary>
        public static string IS_Not_enough_stock_for_0_1_On {
            get {
                return ResourceManager.GetString("IS_Not_enough_stock_for_0_1_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order placed successfully, the order serial is {0} 的當地語系化字串。
        /// </summary>
        public static string IS_Order_placed_successfully_t {
            get {
                return ResourceManager.GetString("IS_Order_placed_successfully_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The price of {0}:{1} has changed from {2} to {3}
        ///Still placing order? 的當地語系化字串。
        /// </summary>
        public static string IS_The_price_of_0_1_has_change {
            get {
                return ResourceManager.GetString("IS_The_price_of_0_1_has_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Price:
        ///{0} 的當地語系化字串。
        /// </summary>
        public static string IS_Total_Price_0 {
            get {
                return ResourceManager.GetString("IS_Total_Price_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Quantity:
        ///{0} 的當地語系化字串。
        /// </summary>
        public static string IS_Total_Quantity_0 {
            get {
                return ResourceManager.GetString("IS_Total_Quantity_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item successfully deleted 的當地語系化字串。
        /// </summary>
        public static string Item_successfully_deleted {
            get {
                return ResourceManager.GetString("Item_successfully_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap languageimage {
            get {
                object obj = ResourceManager.GetObject("languageimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Latitude must be between -90 and 90.Invalid Input 的當地語系化字串。
        /// </summary>
        public static string Latitude_must_be_between_90_an {
            get {
                return ResourceManager.GetString("Latitude_must_be_between_90_an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location 的當地語系化字串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location matches. Closing the form. 的當地語系化字串。
        /// </summary>
        public static string Location_matches_Closing_the_f {
            get {
                return ResourceManager.GetString("Location_matches_Closing_the_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login name or Access level has not been entered. 的當地語系化字串。
        /// </summary>
        public static string Login_name_or_Access_level_has {
            get {
                return ResourceManager.GetString("Login_name_or_Access_level_has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap LoGoLeGend {
            get {
                object obj = ResourceManager.GetObject("LoGoLeGend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Longitude must be between -180 and 180.Invalid Input 的當地語系化字串。
        /// </summary>
        public static string Longitude_must_be_between_180_ {
            get {
                return ResourceManager.GetString("Longitude_must_be_between_180_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Message 的當地語系化字串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Missging data! 的當地語系化字串。
        /// </summary>
        public static string Missging_data {
            get {
                return ResourceManager.GetString("Missging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modify Information 的當地語系化字串。
        /// </summary>
        public static string Modify_Information {
            get {
                return ResourceManager.GetString("Modify_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No cell has been clicked yet. 的當地語系化字串。
        /// </summary>
        public static string No_cell_has_been_clicked_yet {
            get {
                return ResourceManager.GetString("No_cell_has_been_clicked_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No data found 的當地語系化字串。
        /// </summary>
        public static string No_data_found {
            get {
                return ResourceManager.GetString("No_data_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No data to export 的當地語系化字串。
        /// </summary>
        public static string No_data_to_export {
            get {
                return ResourceManager.GetString("No_data_to_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No data to save 的當地語系化字串。
        /// </summary>
        public static string No_data_to_save {
            get {
                return ResourceManager.GetString("No_data_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No DealerID or StaffID 的當地語系化字串。
        /// </summary>
        public static string No_DealerID_or_StaffID {
            get {
                return ResourceManager.GetString("No_DealerID_or_StaffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No item in cart 的當地語系化字串。
        /// </summary>
        public static string No_item_in_cart {
            get {
                return ResourceManager.GetString("No_item_in_cart", resourceCulture);
            }
        }
        public static string sncbe
        {
            get
            {
                return ResourceManager.GetString("sncbe", resourceCulture);
            }
        }

        public static string pncbe
        {
            get
            {
                return ResourceManager.GetString("pncbe", resourceCulture);
            }
        }

        public static string lnaepcann
        {
            get
            {
                return ResourceManager.GetString("lnaepcann", resourceCulture);
            }
        }

        public static string ntfdrcr
        {
            get
            {
                return ResourceManager.GetString("ntfdrcr", resourceCulture);
            }
        }

        public static string ppad
        {
            get
            {
                return ResourceManager.GetString("ppad", resourceCulture);
            }
        }

        public static string nr
        {
            get
            {
                return ResourceManager.GetString("nr", resourceCulture);
            }
        }

        public static string nlae
        {
            get
            {
                return ResourceManager.GetString("nlae", resourceCulture);
            }
        }

        public static string dywanw
        {
            get
            {
                return ResourceManager.GetString("dywanw", resourceCulture);
            }
        }

        public static string dywand
        {
            get
            {
                return ResourceManager.GetString("dywand", resourceCulture);
            }
        }

        public static string aysatl
        {
            get
            {
                return ResourceManager.GetString("aysatl", resourceCulture);
            }
        }

        public static string dywtcana
        {
            get
            {
                return ResourceManager.GetString("dywtcana", resourceCulture);
            }
        }



        public static string dywtas
        {
            get
            {
                return ResourceManager.GetString("dywtas", resourceCulture);
            }
        }

        public static string dywtanw
        {
            get
            {
                return ResourceManager.GetString("dywtanw", resourceCulture);
            }
        }

        public static string dywtans
        {
            get
            {
                return ResourceManager.GetString("dywtans", resourceCulture);
            }
        }

        public static string peavea
        {
            get
            {
                return ResourceManager.GetString("peavea", resourceCulture);
            }
        }


        /// <summary>
        ///   查詢類似 No. of bundles 的當地語系化字串。
        /// </summary>
        public static string No_of_bundles {
            get {
                return ResourceManager.GetString("No_of_bundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No Order to Collect 的當地語系化字串。
        /// </summary>
        public static string No_Order_to_Collect {
            get {
                return ResourceManager.GetString("No_Order_to_Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No path selected 的當地語系化字串。
        /// </summary>
        public static string No_path_selected {
            get {
                return ResourceManager.GetString("No_path_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No rows available in the restock list. 的當地語系化字串。
        /// </summary>
        public static string No_rows_available_in_the_resto {
            get {
                return ResourceManager.GetString("No_rows_available_in_the_resto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No rows available to move. 的當地語系化字串。
        /// </summary>
        public static string No_rows_available_to_move {
            get {
                return ResourceManager.GetString("No_rows_available_to_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No rows were processed. 的當地語系化字串。
        /// </summary>
        public static string No_rows_were_processed {
            get {
                return ResourceManager.GetString("No_rows_were_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No saleArea 的當地語系化字串。
        /// </summary>
        public static string No_saleArea {
            get {
                return ResourceManager.GetString("No_saleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No stock found 的當地語系化字串。
        /// </summary>
        public static string No_stock_found {
            get {
                return ResourceManager.GetString("No_stock_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OfficeAddress 的當地語系化字串。
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 only number! 的當地語系化字串。
        /// </summary>
        public static string only_number {
            get {
                return ResourceManager.GetString("only_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Only spaces and letters are allowed! 的當地語系化字串。
        /// </summary>
        public static string Only_spaces_and_letters_are_al {
            get {
                return ResourceManager.GetString("Only_spaces_and_letters_are_al", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order can not be deleted 的當地語系化字串。
        /// </summary>
        public static string Order_can_not_be_deleted {
            get {
                return ResourceManager.GetString("Order_can_not_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Create 的當地語系化字串。
        /// </summary>
        public static string Order_Create {
            get {
                return ResourceManager.GetString("Order_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Deleted 的當地語系化字串。
        /// </summary>
        public static string Order_Deleted {
            get {
                return ResourceManager.GetString("Order_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Edit 的當地語系化字串。
        /// </summary>
        public static string Order_Edit {
            get {
                return ResourceManager.GetString("Order_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Items Assigned to Collect 的當地語系化字串。
        /// </summary>
        public static string Order_Items_Assigned_to_Collec {
            get {
                return ResourceManager.GetString("Order_Items_Assigned_to_Collec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Record 的當地語系化字串。
        /// </summary>
        public static string Order_Record {
            get {
                return ResourceManager.GetString("Order_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OrderItem 的當地語系化字串。
        /// </summary>
        public static string OrderItem {
            get {
                return ResourceManager.GetString("OrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OUR ORDER NO. 的當地語系化字串。
        /// </summary>
        public static string OUR_ORDER_NO {
            get {
                return ResourceManager.GetString("OUR_ORDER_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Part No. 的當地語系化字串。
        /// </summary>
        public static string Part_No {
            get {
                return ResourceManager.GetString("Part_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phone number cannot exceed 20 digits. 的當地語系化字串。
        /// </summary>
        public static string Phone_number_cannot_exceed_20_ {
            get {
                return ResourceManager.GetString("Phone_number_cannot_exceed_20_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Place Order 的當地語系化字串。
        /// </summary>
        public static string Place_Order {
            get {
                return ResourceManager.GetString("Place_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please contact us to reset your password.
        ///    tel for Hong Kong: 2595-8333
        ///    tel for China: 012-3456-7890
        ///    email: it@legendmotor.com
        ///Opening Hours: 9am - 6pm daily incl. public holiday. 的當地語系化字串。
        /// </summary>
        public static string Please_contact_us_to_reset_you {
            get {
                return ResourceManager.GetString("Please_contact_us_to_reset_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a maximum of 20 digits! 的當地語系化字串。
        /// </summary>
        public static string Please_enter_a_maximum_of_20_d {
            get {
                return ResourceManager.GetString("Please_enter_a_maximum_of_20_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a valid email address! 的當地語系化字串。
        /// </summary>
        public static string Please_enter_a_valid_email_add {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_email_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter full data! 的當地語系化字串。
        /// </summary>
        public static string Please_enter_full_data {
            get {
                return ResourceManager.GetString("Please_enter_full_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter valid numeric values for latitude and longitude.Invalid Input 的當地語系化字串。
        /// </summary>
        public static string Please_enter_valid_numeric_val {
            get {
                return ResourceManager.GetString("Please_enter_valid_numeric_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter values in at least one of the fields. 的當地語系化字串。
        /// </summary>
        public static string Please_enter_values_in_at_leas {
            get {
                return ResourceManager.GetString("Please_enter_values_in_at_leas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your name 的當地語系化字串。
        /// </summary>
        public static string Please_enter_your_name {
            get {
                return ResourceManager.GetString("Please_enter_your_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please fill in all information 的當地語系化字串。
        /// </summary>
        public static string Please_fill_in_all_information {
            get {
                return ResourceManager.GetString("Please_fill_in_all_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please fill in all the required information! 的當地語系化字串。
        /// </summary>
        public static string Please_fill_in_all_the_require {
            get {
                return ResourceManager.GetString("Please_fill_in_all_the_require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input the Number of Bundles 的當地語系化字串。
        /// </summary>
        public static string Please_input_the_Number_of_Bun {
            get {
                return ResourceManager.GetString("Please_input_the_Number_of_Bun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please provide both Department Name and Department Email! 的當地語系化字串。
        /// </summary>
        public static string Please_provide_both_Department {
            get {
                return ResourceManager.GetString("Please_provide_both_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please provide complete data 的當地語系化字串。
        /// </summary>
        public static string Please_provide_complete_data {
            get {
                return ResourceManager.GetString("Please_provide_complete_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please provide Location! 的當地語系化字串。
        /// </summary>
        public static string Please_provide_Location {
            get {
                return ResourceManager.GetString("Please_provide_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a gemder! 的當地語系化字串。
        /// </summary>
        public static string Please_select_a_gemder {
            get {
                return ResourceManager.GetString("Please_select_a_gemder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a Order 的當地語系化字串。
        /// </summary>
        public static string Please_select_a_Order {
            get {
                return ResourceManager.GetString("Please_select_a_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a row to move. 的當地語系化字串。
        /// </summary>
        public static string Please_select_a_row_to_move {
            get {
                return ResourceManager.GetString("Please_select_a_row_to_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a spare 的當地語系化字串。
        /// </summary>
        public static string Please_select_a_spare {
            get {
                return ResourceManager.GetString("Please_select_a_spare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select an account option! 的當地語系化字串。
        /// </summary>
        public static string Please_select_an_account_optio {
            get {
                return ResourceManager.GetString("Please_select_an_account_optio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select an item to delete 的當地語系化字串。
        /// </summary>
        public static string Please_select_an_item_to_delet {
            get {
                return ResourceManager.GetString("Please_select_an_item_to_delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Prev. Qty. 的當地語系化字串。
        /// </summary>
        public static string Prev_Qty {
            get {
                return ResourceManager.GetString("Prev_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price 的當地語系化字串。
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap printing_document_72649 {
            get {
                object obj = ResourceManager.GetObject("printing-document_72649", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Processing 的當地語系化字串。
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Qty 的當地語系化字串。
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Qty to follow 的當地語系化字串。
        /// </summary>
        public static string Qty_to_follow {
            get {
                return ResourceManager.GetString("Qty_to_follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 quantity 的當地語系化字串。
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quantity delivered 的當地語系化字串。
        /// </summary>
        public static string Quantity_delivered {
            get {
                return ResourceManager.GetString("Quantity_delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Re-Stock 的當地語系化字串。
        /// </summary>
        public static string Re_Stock {
            get {
                return ResourceManager.GetString("Re_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Re-Stock Record 的當地語系化字串。
        /// </summary>
        public static string Re_Stock_Record {
            get {
                return ResourceManager.GetString("Re_Stock_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received 的當地語系化字串。
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received in good order 的當地語系化字串。
        /// </summary>
        public static string Received_in_good_order {
            get {
                return ResourceManager.GetString("Received_in_good_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Report 的當地語系化字串。
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Same location 的當地語系化字串。
        /// </summary>
        public static string Same_location {
            get {
                return ResourceManager.GetString("Same_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Saved 的當地語系化字串。
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scanning... 的當地語系化字串。
        /// </summary>
        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 scrap 的當地語系化字串。
        /// </summary>
        public static string scrap {
            get {
                return ResourceManager.GetString("scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ScrapItem Successful! 的當地語系化字串。
        /// </summary>
        public static string ScrapItem_Successful {
            get {
                return ResourceManager.GetString("ScrapItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap search_452448 {
            get {
                object obj = ResourceManager.GetObject("search_452448", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Select language 的當地語系化字串。
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 set stock level 的當地語系化字串。
        /// </summary>
        public static string set_stock_level {
            get {
                return ResourceManager.GetString("set_stock_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting Successful! 的當地語系化字串。
        /// </summary>
        public static string Setting_Successful {
            get {
                return ResourceManager.GetString("Setting_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping 的當地語系化字串。
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Signatory 的當地語系化字串。
        /// </summary>
        public static string Signatory {
            get {
                return ResourceManager.GetString("Signatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Signature 的當地語系化字串。
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simulate server 的當地語系化字串。
        /// </summary>
        public static string Simulate_server {
            get {
                return ResourceManager.GetString("Simulate_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SpareID 的當地語系化字串。
        /// </summary>
        public static string SpareID {
            get {
                return ResourceManager.GetString("SpareID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SpareName 的當地語系化字串。
        /// </summary>
        public static string SpareName {
            get {
                return ResourceManager.GetString("SpareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SpareType 的當地語系化字串。
        /// </summary>
        public static string SpareType {
            get {
                return ResourceManager.GetString("SpareType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 StaffID 的當地語系化字串。
        /// </summary>
        public static string StaffID {
            get {
                return ResourceManager.GetString("StaffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 StaffID not found for current user. 的當地語系化字串。
        /// </summary>
        public static string StaffID_not_found_for_current_ {
            get {
                return ResourceManager.GetString("StaffID_not_found_for_current_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 succeed! 的當地語系化字串。
        /// </summary>
        public static string succeed {
            get {
                return ResourceManager.GetString("succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Succeed! 的當地語系化字串。
        /// </summary>
        public static string Succeed0 {
            get {
                return ResourceManager.GetString("Succeed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Success 的當地語系化字串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Success! 的當地語系化字串。
        /// </summary>
        public static string Success0 {
            get {
                return ResourceManager.GetString("Success0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 success 的當地語系化字串。
        /// </summary>
        public static string success1 {
            get {
                return ResourceManager.GetString("success1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successful add! 的當地語系化字串。
        /// </summary>
        public static string Successful_add {
            get {
                return ResourceManager.GetString("Successful_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successful ADD, your added new spare ID is  的當地語系化字串。
        /// </summary>
        public static string Successful_ADD_your_added_new_ {
            get {
                return ResourceManager.GetString("Successful_ADD_your_added_new_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successful adding! 的當地語系化字串。
        /// </summary>
        public static string Successful_adding {
            get {
                return ResourceManager.GetString("Successful_adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successful creating 的當地語系化字串。
        /// </summary>
        public static string Successful_creating {
            get {
                return ResourceManager.GetString("Successful_creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successful editing 的當地語系化字串。
        /// </summary>
        public static string Successful_editing {
            get {
                return ResourceManager.GetString("Successful_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successful reset password 的當地語系化字串。
        /// </summary>
        public static string Successful_reset_password {
            get {
                return ResourceManager.GetString("Successful_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Supplier Management 的當地語系化字串。
        /// </summary>
        public static string Supplier_Management {
            get {
                return ResourceManager.GetString("Supplier_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SupplierName 的當地語系化字串。
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System is busy please try again later 的當地語系化字串。
        /// </summary>
        public static string System_is_busy_please_try_agai {
            get {
                return ResourceManager.GetString("System_is_busy_please_try_agai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The coordinates (0, 0) are known as Null Island, a location in the Gulf of Guinea where the equator and prime meridian intersect. 的當地語系化字串。
        /// </summary>
        public static string The_coordinates_0_0_are_known_ {
            get {
                return ResourceManager.GetString("The_coordinates_0_0_are_known_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The current order number is:  的當地語系化字串。
        /// </summary>
        public static string The_current_order_number_is {
            get {
                return ResourceManager.GetString("The_current_order_number_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The entered values are too large or too small.Invalid Input 的當地語系化字串。
        /// </summary>
        public static string The_entered_values_are_too_lar {
            get {
                return ResourceManager.GetString("The_entered_values_are_too_lar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The language change will take full effect the next time you start the program. 的當地語系化字串。
        /// </summary>
        public static string The_language_change_will_take_ {
            get {
                return ResourceManager.GetString("The_language_change_will_take_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The old password does not match, please re-enter! 的當地語系化字串。
        /// </summary>
        public static string The_old_password_does_not_matc {
            get {
                return ResourceManager.GetString("The_old_password_does_not_matc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The password entered twice is different, please re-enter! 的當地語系化字串。
        /// </summary>
        public static string The_password_entered_twice_is_ {
            get {
                return ResourceManager.GetString("The_password_entered_twice_is_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The settings have been saved.
        /// 的當地語系化字串。
        /// </summary>
        public static string The_settings_have_been_saved {
            get {
                return ResourceManager.GetString("The_settings_have_been_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The spare is not in the collect list 的當地語系化字串。
        /// </summary>
        public static string The_spare_is_not_in_the_collec {
            get {
                return ResourceManager.GetString("The_spare_is_not_in_the_collec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This invoice create at 的當地語系化字串。
        /// </summary>
        public static string This_invoice_create_at {
            get {
                return ResourceManager.GetString("This_invoice_create_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 this order is finfshed 的當地語系化字串。
        /// </summary>
        public static string this_order_is_finfshed {
            get {
                return ResourceManager.GetString("this_order_is_finfshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total price ($) 的當地語系化字串。
        /// </summary>
        public static string Total_price {
            get {
                return ResourceManager.GetString("Total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total weight 的當地語系化字串。
        /// </summary>
        public static string Total_weight {
            get {
                return ResourceManager.GetString("Total_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unavailable 的當地語系化字串。
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unit price ($) 的當地語系化字串。
        /// </summary>
        public static string Unit_price {
            get {
                return ResourceManager.GetString("Unit_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown State 的當地語系化字串。
        /// </summary>
        public static string Unknown_State {
            get {
                return ResourceManager.GetString("Unknown_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown state 的當地語系化字串。
        /// </summary>
        public static string Unknown_state0 {
            get {
                return ResourceManager.GetString("Unknown_state0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Management 的當地語系化字串。
        /// </summary>
        public static string User_Management {
            get {
                return ResourceManager.GetString("User_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Waiting 的當地語系化字串。
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WarehouseID not found for current staff. 的當地語系化字串。
        /// </summary>
        public static string WarehouseID_not_found_for_curr {
            get {
                return ResourceManager.GetString("WarehouseID_not_found_for_curr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning 的當地語系化字串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your name: 的當地語系化字串。
        /// </summary>
        public static string Your_name {
            get {
                return ResourceManager.GetString("Your_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 YOUR ORDER NO. 的當地語系化字串。
        /// </summary>
        public static string YOUR_ORDER_NO {
            get {
                return ResourceManager.GetString("YOUR_ORDER_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 your working warehouse 的當地語系化字串。
        /// </summary>
        public static string your_working_warehouse {
            get {
                return ResourceManager.GetString("your_working_warehouse", resourceCulture);
            }
        }
    }
}
